### ISSUE TITLE
Problem with ASCII armor integrity check

### ISSUE THREAD

**Issue by MaximilianA** [Airmail/AirmailPlugIn-Framework#11]
Sending encrypted mail I had the issue that the reeive had the following error message:
﻿Error: Ascii armor integrity check on message failed: '' should be 'KXL4'

(checksum naturally different every time though)

Problem is that the checksum is acutally missing when the email was sent with the Airmail plugin
Example:
WNhyDtUge3TLA46KZjuOu3tA=
-----END PGP MESSAGE-----

Normally the checksum for the integrity check is between the "=" and the "-----END PGP MESSAGE-----"

I personally tried it with using Mailvelope as the receiver to decrypt the message.

**Comment by stopdesign** [comment]
Not yet fixed.

**Comment by publicarray** [comment]
I get `Error! Could not read this encrypted message: Error: Ascii armor integrity check on message failed: '' should be 'eSat'` in Mailvelope when trying to decrypt

**Comment by shtirlic** [comment]
Please try with my pull request https://github.com/Airmail/AirmailPlugIn-Framework/pull/20

**Comment by FlxVctr** [comment]
This is still an issue with the plugin provided here: http://docs.airmailapp.com/airmail-for-mac/plugins-airmail-for-macos

**Comment by tomholub** [comment]
Still seems to be an issue as of now, people are sending me messages that miss the checksum.
