### ISSUE TITLE
question for mantainers - is this (working crypto) being actually mantained ? 

### ISSUE THREAD

**Issue by AntonioMeireles** [Airmail/AirmailPlugIn-Framework#19]
@Bloophub: let's talk straight - crypto (PGP and mostly s/mime) is a basic requirement in most, if not all, enterprise environments. IF Airmail really wants to be take seriously in those it just NEEDS  to support it out of the box. the amount of [progress](https://github.com/Bloophub) in this front lately casts serious doubts about upstreams' commitment to the product as a whole IMHO... and that's really sad because working crypto is probably right now the key feature Airmail lacks. 

thoughts ?

**Comment by KodaKoder** [comment]
the plugin is maintained
and also open source for any improvements
