### ISSUE TITLE
PGP plugin is not recognized by Airmail 3

### ISSUE THREAD

**Issue by mmoayyed** [Airmail/AirmailPlugIn-Framework#25]
I am running Airmail 3.0 367. Followed the instructions to download and install the PGP plugin. (Copied the bundle to the directory, exited and restarted the app) The bundle is not recognized and it's never listed in the plugins screen.

**Comment by mvmaasakkers** [comment]
Why was this closed? Is this resolved? I still have this issue atm.

**Comment by stelfrich** [comment]
> I still have this issue atm.

I can confirm @mvmaasakkers' and @mmoayyed's observation: the plugin is not recognized after following the described procedure. Any news?

**Comment by bjornharvold** [comment]
Same here

**Comment by Bert-Jan53** [comment]
Still the same

**Comment by anunayk** [comment]
I am facing the same issue too.

**Comment by alexandernst** [comment]
You must install https://gpgtools.org
